### ISSUE TITLE
[PE-D] Able to create an interview for a person that does not exist by editing JSON

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-W11-2/tp#116]
By editing the JSON, I'm able to have an interview for a non-existent person.

The person list:
![Screenshot 2022-04-01 at 2.44.48 PM.png](https://raw.githubusercontent.com/bryans17/ped/main/files/765a1f1f-87e9-447c-b9a7-79cfd6ea6e7b.png)

The interview list:
![Screenshot 2022-04-01 at 2.45.02 PM.png](https://raw.githubusercontent.com/bryans17/ped/main/files/63f9b86c-19b5-446c-881a-addbc57a1b5e.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: bryans17/ped#5

**Comment by imrajsinghsandhu** [comment]
The error here is that even though the person does not exist in the database, you are still able to add an interview for the missing person. This flaw is not to expose that you can edit the JSON file, rather its that there does not exist a check to see if the person in the interview objects actually exists.
